{
 "title": "Prometheus Redis",
 "description": "Prometheus dashboard for Redis servers",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(redis_up,instance)"
   },
   { "name": "addr", "query": "label_values(redis_up, addr)" }
  ]
 },
 "panels": [
  {
   "title": "Redis Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_up{addr=\"$addr\"}",
     "legendFormat": "Redis Status"
    }
   ]
  },
  {
   "title": "Redis Replication",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_slaves{addr=\"addr\"}",
     "legendFormat": "connected_slaves"
    },
    {
     "expr": "redis_master_repl_offset{addr=\"$addr\"}",
     "legendFormat": "master_repl_offset"
    },
    {
     "expr": "redis_repl_backlog_active{addr=\"$addr\"}",
     "legendFormat": "repl_backlog_active"
    },
    {
     "expr": "redis_repl_backlog_first_byte_offset{addr=\"$addr\"}",
     "legendFormat": "repl_backlog_first_byte_offset"
    },
    {
     "expr": "redis_repl_backlog_histlen{addr=\"$addr\"}",
     "legendFormat": "repl_backlog_histlen"
    },
    {
     "expr": "redis_replication_backlog_bytes{addr=\"$addr\"}",
     "legendFormat": "repl_backlog_bytes"
    }
   ]
  },
  {
   "title": "Redis Persistence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_aof_base_size_bytes{addr=\"$addr\"}",
     "legendFormat": "aof_base_size"
    },
    {
     "expr": "redis_aof_buffer_length{addr=\"$addr\"}",
     "legendFormat": "aof_buffer_length"
    },
    {
     "expr": "redis_aof_current_size_bytes{addr=\"$addr\"}",
     "legendFormat": "aof_current_size"
    },
    {
     "expr": "redis_aof_delayed_fsync{addr=\"$addr\"}",
     "legendFormat": "aof_delayed_fsync"
    },
    {
     "expr": "redis_aof_rewrite_buffer_length{addr=\"$addr\"}",
     "legendFormat": "aof_rewrite_buffer_length"
    },
    {
     "expr": "redis_rdb_changes_since_last_save{addr=\"$addr\"}",
     "legendFormat": "rdb_changes_since_last_save"
    },
    {
     "expr": "redis_rdb_last_save_timestamp_seconds{addr=\"$addr\"}",
     "legendFormat": "rdb_last_save_time"
    }
   ]
  },
  {
   "title": "Redis WriteStatus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_evicted_keys_total{addr=\"$addr\"}",
     "legendFormat": "evicted_keys"
    },
    {
     "expr": "redis_expired_keys_total{addr=\"$addr\"}",
     "legendFormat": "expired_keys"
    },
    {
     "expr": "redis_instantaneous_output_kbps{addr=\"$addr\"}",
     "legendFormat": "instantaneous_output_kbps"
    },
    {
     "expr": "redis_instantaneous_ops_per_sec{addr=\"$addr\"}",
     "legendFormat": "instantaneous_ops_per_sec"
    },
    {
     "expr": "redis_instantaneous_input_kbps{addr=\"$addr\"}",
     "legendFormat": "instantaneous_input_kbps"
    },
    {
     "expr": "redis_keyspace_hits_total{addr=\"$addr\"}",
     "legendFormat": "keyspace_hits"
    },
    {
     "expr": "redis_keyspace_misses_total{addr=\"$addr\"}",
     "legendFormat": "keyspace_misses"
    },
    {
     "expr": "redis_latest_fork_usec{addr=\"$addr\"}",
     "legendFormat": "latest_fork_usec"
    },
    {
     "expr": "redis_pubsub_channels{addr=\"$addr\"}",
     "legendFormat": "pubsub_channels"
    },
    {
     "expr": "redis_pubsub_patterns{addr=\"$addr\"}",
     "legendFormat": "pubsub_patterns"
    },
    {
     "expr": "redis_rejected_connections_total{addr=\"$addr\"}",
     "legendFormat": "rejected_connections"
    },
    {
     "expr": "redis_connections_received_total{addr=\"$addr\"}",
     "legendFormat": "connections_received_total"
    },
    {
     "expr": "redis_sync_full{addr=\"$addr\"}",
     "legendFormat": "sync_full"
    },
    {
     "expr": "redis_sync_partial_err{addr=\"$addr\"}",
     "legendFormat": "sync_partial_err"
    },
    {
     "expr": "redis_sync_partial_ok{addr=\"$addr\"}",
     "legendFormat": "sync_partial_ok"
    }
   ]
  },
  {
   "title": "Redis Persistence Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_last_bgsave_status{addr=\"$addr\"}",
     "legendFormat": "rdb_last_bgsave_status"
    },
    {
     "expr": "redis_aof_enabled{addr=\"$addr\"}",
     "legendFormat": "aof_enabled"
    },
    {
     "expr": "redis_aof_last_bgrewrite_status{addr=\"$addr\"}",
     "legendFormat": "aof_last_bgrewrite_status"
    },
    {
     "expr": "redis_aof_last_write_status{addr=\"$addr\"}",
     "legendFormat": "aof_last_write_status"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{addr=\"$addr\"}",
     "legendFormat": "aof_rewrite_in_progress"
    },
    {
     "expr": "redis_aof_rewrite_scheduled{addr=\"$addr\"}",
     "legendFormat": "aof_rewrite_scheduled"
    },
    {
     "expr": "redis_aof_pending_rewrite{addr=\"$addr\"}",
     "legendFormat": "aof_pending_rewrite"
    },
    {
     "expr": "redis_aof_pending_bio_fsync{addr=\"$addr\"}",
     "legendFormat": "aof_pending_bio_fsync"
    },
    {
     "expr": "redis_rdb_bgsave_in_progress{addr=\"$addr\"}",
     "legendFormat": "rdb_bgsave_in_progress"
    },
    {
     "expr": "redis_loading_dump_file{addr=\"$addr\"}",
     "legendFormat": "redis_loading"
    }
   ]
  },
  {
   "title": "Redis Persistence Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_aof_current_rewrite_duration_sec{addr=\"$addr\"}",
     "legendFormat": "aof_current_rewrite_duration_sec"
    },
    {
     "expr": "redis_aof_last_rewrite_duration_sec{addr=\"$addr\"}",
     "legendFormat": "aof_last_rewrite_duration_sec"
    },
    {
     "expr": "redis_rdb_current_bgsave_duration_sec{addr=\"$addr\"}",
     "legendFormat": "rdb_current_bgsave_duration_sec"
    },
    {
     "expr": "redis_rdb_last_bgsave_duration_sec{addr=\"$addr\"}",
     "legendFormat": "rdb_last_bgsave_duration_sec"
    }
   ]
  },
  {
   "title": "Redis Memoey ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{addr=\"$addr\"}",
     "legendFormat": "mem_fragmentation_ratio"
    }
   ]
  },
  {
   "title": "Redis Keyttl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_avg_ttl_seconds{addr=\"$addr\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "RedisInfo",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "repeat": "addr",
   "targets": [
    {
     "expr": "redis_instance_info{addr=\"$addr\"}"
    },
    {
     "expr": "redis_slave_info{addr=\"$addr\"}"
    },
    {
     "expr": "redis_connected_slave_lag_seconds{addr=\"$addr\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "addr" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 31 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{addr=\"$addr\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(redis_memory_used_bytes{addr=\"$addr\"}/redis_config_maxmemory{addr=\"$addr\"})*100"
    }
   ]
  },
  {
   "title": "RedisRole",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_slave_info{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{addr=~\"$addr\"}[5m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=\"$addr\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=\"$addr\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$addr\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{addr=~\"$addr\"} ",
     "legendFormat": "max"
    },
    {
     "expr": "redis_memory_used_lua_bytes{addr=~\"$addr\"}",
     "legendFormat": "used_lua"
    },
    {
     "expr": "redis_memory_used_peak_bytes{addr=~\"$addr\"}",
     "legendFormat": "used_peak"
    },
    {
     "expr": "redis_memory_used_rss_bytes{addr=~\"$addr\"}",
     "legendFormat": "used_rss"
    },
    {
     "expr": "redis_total_system_memory_bytes{addr=~\"$addr\"}",
     "legendFormat": "total_system"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=\"$addr\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=\"$addr\"}[5m])",
     "legendFormat": "{{ output }}"
    },
    {
     "expr": "redis_net_output_bytes_total{addr=\"$addr\"}",
     "legendFormat": "net_output_total"
    },
    {
     "expr": "redis_net_input_bytes_total{addr=\"$addr\"}",
     "legendFormat": "net_input_total"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) - sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{addr=~\"$addr\"} [2m]))",
     "legendFormat": "{{ cmd }}"
    },
    {
     "expr": "increase(redis_commands_processed_total{addr=\"$addr\"} [2m])",
     "legendFormat": "30s_total_command_processed"
    }
   ]
  },
  {
   "title": "RedisClients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_blocked_clients{addr=~\"$addr\"}",
     "legendFormat": "clients_blocked"
    },
    {
     "expr": "redis_client_biggest_input_buf{addr=~\"$addr\"}",
     "legendFormat": "client_biggest_input_buf"
    },
    {
     "expr": "redis_client_longest_output_list{addr=~\"$addr\"}",
     "legendFormat": "client_longest_output_list"
    },
    {
     "expr": "redis_config_maxclients{addr=~\"$addr\"}",
     "legendFormat": "maxclients"
    },
    {
     "expr": "redis_connected_clients{addr=~\"$addr\"}",
     "legendFormat": "connected_clients"
    }
   ]
  },
  {
   "title": "RedisCPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_used_cpu_sys{addr=~\"$addr\"}",
     "legendFormat": "used_cpu_sys"
    },
    {
     "expr": "redis_used_cpu_sys_children{addr=~\"$addr\"}",
     "legendFormat": "used_cpu_sys_children"
    },
    {
     "expr": "redis_used_cpu_user{addr=~\"$addr\"}",
     "legendFormat": "used_cpu_user"
    },
    {
     "expr": "redis_used_cpu_user_children{addr=~\"$addr\"}",
     "legendFormat": "used_cpu_user_children"
    }
   ]
  }
 ]
}